# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\floor1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from floor1_qrc import*
from screeninfo import get_monitors

disp_w = 0
disp_h = 0

for monitor in get_monitors():
    disp_w = monitor.width
    disp_h = monitor.height


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(disp_w, disp_h)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 721, 521))
        self.widget.setStyleSheet("QWidget {\n"
"background-color: #12141C;\n"
"}")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 121, 33))
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color: #5445D0;\n"
"color: white;\n"
"border-radius: 10px;\n"
"text-align: center;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 60, 121, 33))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"background-color: #5445D0;\n"
"color: white;\n"
"border-radius: 10px;\n"
"text-align: center;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(42, 220, 54, 35))
        self.widget_3.setStyleSheet("QWidget {\n"
"border: 2px solid white;\n"
"background-color: #17181D;\n"
"border-bottom-right-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(23, 10, 20, 19))
        self.label_2.setStyleSheet("QLabel {\n"
"color: white;\n"
"border: none;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setGeometry(QtCore.QRect(42, 187, 54, 35))
        self.widget_5.setStyleSheet("QWidget {\n"
"border: 2px solid white;\n"
"background-color: #17181D;\n"
"}")
        self.widget_5.setObjectName("widget_5")
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setGeometry(QtCore.QRect(23, 10, 20, 19))
        self.label_3.setStyleSheet("QLabel {\n"
"color: white;\n"
"border: none;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setGeometry(QtCore.QRect(42, 153, 54, 35))
        self.widget_4.setStyleSheet("QWidget {\n"
"border: 2px solid white;\n"
"background-color: #17181D;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setGeometry(QtCore.QRect(23, 10, 20, 19))
        self.label.setStyleSheet("QLabel {\n"
"color: white;\n"
"border: none;\n"
"}")
        self.label.setObjectName("label")
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setGeometry(QtCore.QRect(42, 119, 54, 35))
        self.widget_6.setStyleSheet("QWidget {\n"
"border: 2px solid white;\n"
"background-color: #DDC523;\n"
"border-top-right-radius: 20px;\n"
"border-top-left-radius: 20px;\n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.label_4 = QtWidgets.QLabel(self.widget_6)
        self.label_4.setGeometry(QtCore.QRect(23, 10, 20, 19))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"border: 0px solid balck;\n"
"text-align: center;\n"
"}")
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.widget_7 = QtWidgets.QWidget(self.widget)
        self.widget_7.setGeometry(QtCore.QRect(42, 310, 54, 35))
        self.widget_7.setStyleSheet("QWidget {\n"
"border: 2px solid white;\n"
"background-color: #17181D;\n"
"border-radius: 13px;\n"
"}")
        self.widget_7.setObjectName("widget_7")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(56, 315, 25, 25))
        self.label_5.setStyleSheet("QLabel {\n"
"border: none;\n"
"}")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/photo/photo/icons8-поиск-500.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(20, 440, 118, 50))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/photo/photo/белый.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.main_holl = QtWidgets.QWidget(self.widget)
        self.main_holl.setGeometry(QtCore.QRect(139, 270, 91, 151))
        self.main_holl.setStyleSheet("QWidget {\n"
"border: 2px solid white;\n"
"border-bottom-left-radius: 35px;\n"
"border-top-left-radius: 35px;\n"
"}")
        self.main_holl.setObjectName("main_holl")
        self.label_25 = QtWidgets.QLabel(self.main_holl)
        self.label_25.setGeometry(QtCore.QRect(20, 50, 61, 61))
        self.label_25.setStyleSheet("color: white;\n"
"border: none;\n"
"text-align: center;\n"
"align-items: center;")
        self.label_25.setObjectName("label_25")
        self.main_holl_2 = QtWidgets.QWidget(self.widget)
        self.main_holl_2.setGeometry(QtCore.QRect(210, 420, 73, 55))
        self.main_holl_2.setStyleSheet("QWidget {\n"
"border: 2px solid #724120;\n"
"background-color: #38261E;\n"
"color: #B0B0C6;\n"
"border-bottom-left-radius: 35px\n"
"}\n"
"\n"
"QWidget:hover {\n"
"background-color: #5A361E;\n"
"border: 2px solid #37A4520;\n"
"}")
        self.main_holl_2.setObjectName("main_holl_2")
        self.label_22 = QtWidgets.QLabel(self.main_holl_2)
        self.label_22.setGeometry(QtCore.QRect(30, 17, 31, 20))
        self.label_22.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    border: none;\n"
"    background: transparent;\n"
"}")
        self.label_22.setObjectName("label_22")
        self.widget_20 = QtWidgets.QWidget(self.widget)
        self.widget_20.setGeometry(QtCore.QRect(320, 258, 191, 43))
        self.widget_20.setStyleSheet("QWidget {\n"
"border: 2px solid white;\n"
"}\n"
"")
        self.widget_20.setObjectName("widget_20")
        self.label_7 = QtWidgets.QLabel(self.widget_20)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 141, 16))
        self.label_7.setStyleSheet("color: white;\n"
"border: none;")
        self.label_7.setObjectName("label_7")
        self.widget_31 = QtWidgets.QWidget(self.widget)
        self.widget_31.setGeometry(QtCore.QRect(190, 70, 3, 200))
        self.widget_31.setStyleSheet("border: 2px solid white;")
        self.widget_31.setObjectName("widget_31")
        self.widget_33 = QtWidgets.QWidget(self.widget)
        self.widget_33.setGeometry(QtCore.QRect(701, 230, 3, 30))
        self.widget_33.setStyleSheet("border: 2px solid white;")
        self.widget_33.setObjectName("widget_33")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 19, 51, 51))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"border: 2px solid #724120;\n"
"background-color: #38261E;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #5A361E;\n"
"border: 2px solid #37A4520;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 19, 41, 51))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"border: 2px solid #724120;\n"
"background-color: #38261E;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #5A361E;\n"
"border: 2px solid #37A4520;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 19, 91, 51))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"border: 2px solid #724120;\n"
"background-color: #38261E;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #5A361E;\n"
"border: 2px solid #37A4520;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(280, 420, 73, 55))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"border: 2px solid #724120;\n"
"background-color: #38261E;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #5A361E;\n"
"border: 2px solid #37A4520;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setGeometry(QtCore.QRect(350, 420, 73, 55))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"border: 2px solid #724120;\n"
"background-color: #38261E;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #5A361E;\n"
"border: 2px solid #37A4520;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setGeometry(QtCore.QRect(420, 420, 73, 55))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"border: 2px solid #724120;\n"
"background-color: #38261E;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #5A361E;\n"
"border: 2px solid #37A4520;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setGeometry(QtCore.QRect(490, 420, 73, 55))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"border: 2px solid #724120;\n"
"background-color: #38261E;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #5A361E;\n"
"border: 2px solid #37A4520;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setGeometry(QtCore.QRect(560, 420, 73, 55))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"border: 2px solid #724120;\n"
"background-color: #38261E;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #5A361E;\n"
"border: 2px solid #37A4520;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setGeometry(QtCore.QRect(630, 420, 73, 55))
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"border: 2px solid #724120;\n"
"background-color: #38261E;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #5A361E;\n"
"border: 2px solid #37A4520;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget)
        self.pushButton_12.setGeometry(QtCore.QRect(662, 390, 41, 31))
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"border: 2px solid #724120;\n"
"background-color: #38261E;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #5A361E;\n"
"border: 2px solid #37A4520;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.widget)
        self.pushButton_13.setGeometry(QtCore.QRect(612, 350, 91, 41))
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"background-color: #1A2925;\n"
"border: 2px solid #213F2C;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #1F3C2B;\n"
"border: 2px solid #27301F;\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget)
        self.pushButton_14.setGeometry(QtCore.QRect(190, 160, 71, 51))
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"background-color: #1A2925;\n"
"border: 2px solid #213F2C;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #1F3C2B;\n"
"border: 2px solid #27301F;\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.widget)
        self.pushButton_15.setGeometry(QtCore.QRect(320, 300, 61, 24))
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"background-color: #1A2925;\n"
"border: 2px solid #213F2C;\n"
"color: white;\n"
"font-size: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #1F3C2B;\n"
"border: 2px solid #27301F;\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(370, 350, 250, 3))
        self.line.setStyleSheet("Line {\n"
"background-color: white;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_16 = QtWidgets.QPushButton(self.widget)
        self.pushButton_16.setGeometry(QtCore.QRect(510, 258, 31, 43))
        self.pushButton_16.setStyleSheet("QPushButton {\n"
"background-color: #1A2925;\n"
"border: 2px solid #213F2C;\n"
"color: white;\n"
"font-size: 11px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #1F3C2B;\n"
"border: 2px solid #27301F;\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.widget)
        self.pushButton_17.setGeometry(QtCore.QRect(320, 130, 61, 101))
        self.pushButton_17.setStyleSheet("QPushButton {\n"
"background-color: #271B32;\n"
"border: 2px solid #50275A;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #472452;\n"
"border: 2px solid #753280;\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.widget)
        self.pushButton_18.setGeometry(QtCore.QRect(442, 130, 61, 101))
        self.pushButton_18.setStyleSheet("QPushButton {\n"
"background-color: #271B32;\n"
"border: 2px solid #50275A;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #472452;\n"
"border: 2px solid #753280;\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.widget)
        self.pushButton_19.setGeometry(QtCore.QRect(320, 322, 61, 31))
        self.pushButton_19.setStyleSheet("QPushButton {\n"
"background-color: #15243B;\n"
"border: 2px solid #17355B;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #16355C;\n"
"border: 2px solid #217CE0;\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.widget)
        self.pushButton_20.setGeometry(QtCore.QRect(540, 258, 164, 43))
        self.pushButton_20.setStyleSheet("QPushButton {\n"
"background-color: #323118;\n"
"border: 2px solid #494814;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #524F12;\n"
"border: 2px solid #89830A;\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.widget)
        self.pushButton_21.setGeometry(QtCore.QRect(502, 130, 41, 101))
        self.pushButton_21.setStyleSheet("QPushButton {\n"
"background-color: #323118;\n"
"border: 2px solid #494814;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #524F12;\n"
"border: 2px solid #89830A;\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.widget)
        self.pushButton_22.setGeometry(QtCore.QRect(320, 19, 201, 111))
        self.pushButton_22.setStyleSheet("QPushButton {\n"
"background-color: #371D24;\n"
"border: 2px solid #63282D;\n"
"color: white;\n"
"font-size: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #582328;\n"
"border: 2px solid #812E32;\n"
"}")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.widget)
        self.pushButton_23.setGeometry(QtCore.QRect(543, 130, 161, 101))
        self.pushButton_23.setStyleSheet("QPushButton {\n"
"background-color: #371D24;\n"
"border: 2px solid #63282D;\n"
"color: white;\n"
"font-size: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #582328;\n"
"border: 2px solid #812E32;\n"
"}")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_22.raise_()
        self.line.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.widget_3.raise_()
        self.widget_5.raise_()
        self.widget_4.raise_()
        self.widget_6.raise_()
        self.widget_7.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.main_holl.raise_()
        self.main_holl_2.raise_()
        self.widget_20.raise_()
        self.widget_31.raise_()
        self.widget_33.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        self.pushButton_15.raise_()
        self.pushButton_16.raise_()
        self.pushButton_17.raise_()
        self.pushButton_18.raise_()
        self.pushButton_19.raise_()
        self.pushButton_20.raise_()
        self.pushButton_21.raise_()
        self.pushButton_23.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "2D навигация"))
        self.pushButton_2.setText(_translate("Form", "3D навигация"))
        self.label_2.setText(_translate("Form", "4"))
        self.label_3.setText(_translate("Form", "3"))
        self.label.setText(_translate("Form", "2"))
        self.label_4.setText(_translate("Form", "1"))
        self.label_25.setText(_translate("Form", "Главный\n"
" холл"))
        self.label_22.setText(_translate("Form", "1.08"))
        self.label_7.setText(_translate("Form", "Кабинет директора"))
        self.pushButton_3.setText(_translate("Form", "1.17"))
        self.pushButton_4.setText(_translate("Form", "1.18"))
        self.pushButton_5.setText(_translate("Form", "1.19"))
        self.pushButton_6.setText(_translate("Form", "1.07"))
        self.pushButton_7.setText(_translate("Form", "1.06"))
        self.pushButton_8.setText(_translate("Form", "1.05"))
        self.pushButton_9.setText(_translate("Form", "1.04"))
        self.pushButton_10.setText(_translate("Form", "1.03"))
        self.pushButton_11.setText(_translate("Form", "1.02"))
        self.pushButton_12.setText(_translate("Form", "1.01"))
        self.pushButton_13.setText(_translate("Form", "лестница"))
        self.pushButton_14.setText(_translate("Form", "лестница"))
        self.pushButton_15.setText(_translate("Form", "лестница"))
        self.pushButton_16.setText(_translate("Form", "лес\n"
"тни\n"
"ца"))
        self.pushButton_17.setText(_translate("Form", "гар\n"
"дер\n"
"об"))
        self.pushButton_18.setText(_translate("Form", "гар\n"
"дер\n"
"об"))
        self.pushButton_19.setText(_translate("Form", "туалет"))
        self.pushButton_20.setText(_translate("Form", "служебная зона"))
        self.pushButton_21.setText(_translate("Form", "сл.\n"
" зона"))
        self.pushButton_22.setText(_translate("Form", "Столовая"))
        self.pushButton_23.setText(_translate("Form", "Библиотека"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    Form.setWindowFlag(Qt.FramelessWindowHint)

    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
